POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "doe@email.com",
  "password": "123456",
  "createdAt": "2020-01-01T00:00:00Z",
  "updatedAt": "2020-01-01T00:00:00Z"
}

###
GET http://localhost:8080/api/v1/users

###
GET http://localhost:8080/api/v1/users/77f2fad7-2a50-4310-8404-7d7ba6f8a756

###
PATCH http://localhost:8080/api/v1/users/77f2fad7-2a50-4310-8404-7d7ba6f8a756
Content-Type: application/json

{
  "name": "John Foo",
  "email": "asdasd@email.com",
  "avatar": "https://www.gravatar.com/avatar/00000000000000000000000000000000?d=mp&f=y",
  "password": "54321",
  "oldPassword": "123456"
}

###
DELETE http://localhost:8080/api/v1/users/77f2fad7-2a50-4310-8404-7d7ba6f8a756